name: CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build with Jekyll
        run: bundle exec jekyll build --strict_front_matter
        env:
          JEKYLL_ENV: production

      - name: Check internal links
        run: bundle exec htmlproofer ./_site --disable-external --checks Links
